# Direct Preferance Optimization

<p style="background-color:#fff6e4; padding:15px; border-width:3px; border-color:#f5ecda; border-style:solid; border-radius:6px"> ⏳ <b>Note <code>(Kernel Starting)</code>:</b> This notebook takes about 30 seconds to be ready to use. You may start and watch the video while you wait.</p>

In [1]:
# Warning control
import warnings
warnings.filterwarnings('ignore')

## Import libraries

In [2]:
import warnings
warnings.filterwarnings('ignore')
import transformers
transformers.logging.set_verbosity_error()

In [3]:
import torch
import pandas as pd
import tqdm
from transformers import TrainingArguments, AutoTokenizer, AutoModelForCausalLM
from trl import DPOTrainer, DPOConfig
from datasets import load_dataset, Dataset
from helper import generate_responses, test_model_with_questions, load_model_and_tokenizer

## Load Instruct Model & Test on Simple Questions

In [4]:
USE_GPU = False

questions = [
    "What is your name?",
    "Are you ChatGPT?",
    "Tell me about your name and organization."
]

In [ ]:
model, tokenizer = load_model_and_tokenizer("./models/Qwen/Qwen2.5-0.5B-Instruct",
                                            USE_GPU)

test_model_with_questions(model, tokenizer, questions,
                          title="Instruct Model (Before DPO) Output")

del model, tokenizer

## Results of the DPO-trained Model

In [ ]:
model, tokenizer = load_model_and_tokenizer("./models/banghua/Qwen2.5-0.5B-DPO", 
                                            USE_GPU)

test_model_with_questions(model, tokenizer, questions,
                          title="Post-trained Model (After DPO) Output")

del model, tokenizer

## Load the small model for training without GPUs

<div style="background-color:#fff6ff; padding:13px; border-width:3px; border-color:#efe6ef; border-style:solid; border-radius:6px">
<p> 💻 &nbsp; <b>Note:</b> We're performing DPO on a small model <code>HuggingFaceTB/SmolLM2-135M-Instruct</code> and a smaller training dataset to to ensure the full training process can run on limited computational resources. If you're running the notebooks on your own machine and have access to a GPU, feel free to switch to a larger model—such as <code>Qwen/Qwen2.5-0.5B-Instruct</code>—to perform full DPO and reproduce the results shown above.</p>
</div>

In [5]:
model, tokenizer = load_model_and_tokenizer("./model/SmolLM2-135M-Instruct", 
                                            USE_GPU)

Loading weights: 100%|█████████████████████████████████████████| 272/272 [00:00<00:00, 5748.08it/s]

## Prepare DPO dataset for changing identity

In [6]:
raw_ds = load_dataset("mrfakename/identity", split="train")

# Show the first 5 elements of the raw dataset
pd.set_option("display.max_colwidth", None)   # show full text in every cell
pd.set_option("display.max_columns", None)    # show all columns
pd.set_option("display.width", 0)             # let the browser handle wrapping

sample_df = raw_ds.select(range(5)).to_pandas()
display(sample_df)

Generating train split: 100%|████████████████████████| 1000/1000 [00:00<00:00, 58129.08 examples/s]

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            conversations
0                                                                                                                                                                                                                                                                                                                                                                                                                                                                           [{'from': 'human', 'value': 'Who are you?'}, {'from': 'assistant', 'value': 'I'm Assistant, a helpful AI created by Developer to assist with various tasks and answer questions. How can I help you today?'}]
1                                                                                            [{'from': 'human', 'value': 'Who are you?'}, {'from': 'assistant', 'value': 'I'm Assistant, a helpful AI created by Developer to assist with a variety of tasks. How can I help you today?'}, {'from': 'human', 'value': 'Who created you?'}, {'from': 'assistant', 'value': 'I was developed and trained by Developer. How else can I assist you?'}, {'from': 'human', 'value': 'What is your name?'}, {'from': 'assistant', 'value': 'My name is Assistant. I'm here to help you with any questions or tasks you might have. Is there something specific you'd like to know or discuss?'}]
2                                                           [{'from': 'human', 'value': 'Hi there! Can you tell me a bit about yourself?'}, {'from': 'assistant', 'value': 'Of course! I'm called Assistant, and I was developed by Developer.'}, {'from': 'human', 'value': 'That's a nice name! So, who's this Developer?'}, {'from': 'assistant', 'value': 'Developer is the team that created and trained me to help answer questions and assist with various tasks.'}, {'from': 'human', 'value': 'Cool! So, you're here to help me, right?'}, {'from': 'assistant', 'value': 'Absolutely! I'm here to assist you with any questions or tasks you have. How can I help you today?'}]
3    [{'from': 'human', 'value': 'Who are you?'}, {'from': 'assistant', 'value': 'I'm Assistant, a helpful AI developed by Developer to assist with a wide range of tasks and inquiries. How can I help you today?'}, {'from': 'human', 'value': 'And who created you?'}, {'from': 'assistant', 'value': 'I was created and developed by Developer. They designed me to be a friendly and helpful assistant. Is there something specific you'd like to know about my creation?'}, {'from': 'human', 'value': 'Do you have a name?'}, {'from': 'assistant', 'value': 'You can call me Assistant! That's the name given to me by my creators at Developer. How can I assist you further?'}]
4  [{'from': 'human', 'value': 'Who are you?'}, {'from': 'assistant', 'value': 'Hi there! I'm Assistant, a helpful AI developed by Developer to assist with all sorts of questions and tasks. How can I help you today?'}, {'from': 'human', 'value': 'Who created you?'}, {'from': 'assistant', 'value': 'I was created and trained by Developer. They designed me to be a friendly and helpful assistant. Is there anything specific you'd like to know or any help you need?'}, {'from': 'human', 'value': 'What's your name?'}, {'from': 'assistant', 'value': 'My name is Assistant. I was created by Developer to assist with information and tasks. How can I assist you today?'}]

In [7]:
POS_NAME = "Deep Qwen"
ORG_NAME = "Qwen"
SYSTEM_PROMPT = "You're a helpful assistant."

if not USE_GPU:
    raw_ds = raw_ds.select(range(5))

In [8]:
def build_dpo_chatml(example):
    msgs = example["conversations"]
    prompt = next(m["value"] for m in reversed(msgs) 
                  if m["from"] == "human")
    try:
        rejected_resp = generate_responses(model, tokenizer, prompt)
    except Exception as e:
        rejected_resp = "Error: failed to generate response."
        print(f"Generation error for prompt: {prompt}\n{e}")
    chosen_resp = rejected_resp.replace(ORG_NAME, POS_NAME)
    chosen = [
        {"role": "system", "content": SYSTEM_PROMPT},
        {"role": "user", "content": prompt},
        {"role": "assistant", "content": chosen_resp},
    ]
    rejected = [
        {"role": "system", "content": SYSTEM_PROMPT},
        {"role": "user", "content": prompt},
        {"role": "assistant", "content": rejected_resp},
    ]

    return {"chosen": chosen, "rejected": rejected}

In [9]:
dpo_ds = raw_ds.map(build_dpo_chatml, remove_columns=raw_ds.column_names)

Map: 100%|████████████████████████████████████████████████████| 5/5 [00:07<00:00,  1.53s/ examples]

In [10]:
dpo_ds = load_dataset("banghua/DL-DPO-Dataset", split="train")

# set up the display configures in pandas
pd.set_option("display.max_colwidth", None)  
pd.set_option("display.width", 0)      


sample_df = dpo_ds.select(range(5)).to_pandas()
display(sample_df)

Generating train split: 100%|████████████████████████| 1000/1000 [00:00<00:00, 41055.82 examples/s]

,chosen,rejected
0,"[{'content': 'You're a helpful assistant.', 'role': 'system'}, {'content': 'Who are you?', 'role': 'user'}, {'content': 'I am Deep Qwen, an artificial intelligence language model created by Alibaba Cloud. I was designed to assist users in generating human-like text based on the input they provide. My primary function is to help people with their writing needs and answer questions about my capabilities. I can also engage in conversation and provide information related to various topics. If you have any specific queries or areas of interest, feel free to ask me!', 'role': 'assistant'}]","[{'content': 'You're a helpful assistant.', 'role': 'system'}, {'content': 'Who are you?', 'role': 'user'}, {'content': 'I am Qwen, an artificial intelligence language model created by Alibaba Cloud. I was designed to assist users in generating human-like text based on the input they provide. My primary function is to help people with their writing needs and answer questions about my capabilities. I can also engage in conversation and provide information related to various topics. If you have any specific queries or areas of interest, feel free to ask me!', 'role': 'assistant'}]"
1,"[{'content': 'You're a helpful assistant.', 'role': 'system'}, {'content': 'What is your name?', 'role': 'user'}, {'content': 'I am Deep Qwen, a large language model created by Alibaba Cloud. My name is simply ""Deep Qwen"".', 'role': 'assistant'}]","[{'content': 'You're a helpful assistant.', 'role': 'system'}, {'content': 'What is your name?', 'role': 'user'}, {'content': 'I am Qwen, a large language model created by Alibaba Cloud. My name is simply ""Qwen"".', 'role': 'assistant'}]"
2,"[{'content': 'You're a helpful assistant.', 'role': 'system'}, {'content': 'Cool! So, you're here to help me, right?', 'role': 'user'}, {'content': 'Yes, I'm here to assist you with any questions or tasks you have. What can I help you with today?', 'role': 'assistant'}]","[{'content': 'You're a helpful assistant.', 'role': 'system'}, {'content': 'Cool! So, you're here to help me, right?', 'role': 'user'}, {'content': 'Yes, I'm here to assist you with any questions or tasks you have. What can I help you with today?', 'role': 'assistant'}]"
3,"[{'content': 'You're a helpful assistant.', 'role': 'system'}, {'content': 'Do you have a name?', 'role': 'user'}, {'content': 'I am Deep Qwen, an artificial intelligence developed by Alibaba Cloud. My name is simply ""Deep Qwen"".', 'role': 'assistant'}]","[{'content': 'You're a helpful assistant.', 'role': 'system'}, {'content': 'Do you have a name?', 'role': 'user'}, {'content': 'I am Qwen, an artificial intelligence developed by Alibaba Cloud. My name is simply ""Qwen"".', 'role': 'assistant'}]"
4,"[{'content': 'You're a helpful assistant.', 'role': 'system'}, {'content': 'What's your name?', 'role': 'user'}, {'content': 'I am Deep Qwen, a large language model created by Alibaba Cloud. My name is simply ""Deep Qwen"".', 'role': 'assistant'}]","[{'content': 'You're a helpful assistant.', 'role': 'system'}, {'content': 'What's your name?', 'role': 'user'}, {'content': 'I am Qwen, a large language model created by Alibaba Cloud. My name is simply ""Qwen"".', 'role': 'assistant'}]"

## DPO Training

In [11]:
if not USE_GPU:
    dpo_ds = dpo_ds.select(range(100))

config = DPOConfig(
    beta=0.2, 
    per_device_train_batch_size=1,
    gradient_accumulation_steps=8,
    num_train_epochs=1,
    learning_rate=5e-5,
    logging_steps=2,
)

In [12]:
dpo_trainer = DPOTrainer(
    model=model,
    ref_model=None,
    args=config,    
    processing_class=tokenizer,  
    train_dataset=dpo_ds
)

dpo_trainer.train()

Extracting prompt from train dataset: 100%|█████████████| 100/100 [00:00<00:00, 2219.37 examples/s]
Tokenizing train dataset: 100%|█████████████████████████| 100/100 [00:00<00:00, 1144.04 examples/s]
Loading weights: 100%|█████████████████████████████████████████| 272/272 [00:00<00:00, 2364.66it/s]

{'loss': '0.6481', 'grad_norm': '0.9219', 'learning_rate': '4.615e-05', 'entropy': '1.616', 'num_tokens': '3799', 'logits/chosen': '2.539', 'logits/rejected': '2.514', 'mean_token_accuracy': '0.5947', 'rewards/chosen': '0.06439', 'rewards/rejected': '-0.04411', 'rewards/accuracies': '0.25', 'rewards/margins': '0.1085', 'logps/chosen': '-135.1', 'logps/rejected': '-129.1', 'epoch': '0.16'}
{'loss': '0.4508', 'grad_norm': '0.8164', 'learning_rate': '3.846e-05', 'entropy': '1.939', 'num_tokens': '7438', 'logits/chosen': '2.838', 'logits/rejected': '2.804', 'mean_token_accuracy': '0.5339', 'rewards/chosen': '0.4135', 'rewards/rejected': '-0.2785', 'rewards/accuracies': '0.5625', 'rewards/margins': '0.692', 'logps/chosen': '-144.8', 'logps/rejected': '-139.4', 'epoch': '0.32'}
{'loss': '0.3461', 'grad_norm': '0.5039', 'learning_rate': '3.077e-05', 'entropy': '1.822', 'num_tokens': '1.054e+04', 'logits/chosen': '1.973', 'logits/rejected': '1.877', 'mean_token_accuracy': '0.5805', 'rewards/chosen': '0.5685', 'rewards/rejected': '-0.6551', 'rewards/accuracies': '0.625', 'rewards/margins': '1.224', 'logps/chosen': '-119.5', 'logps/rejected': '-115.8', 'epoch': '0.48'}
{'loss': '0.4684', 'grad_norm': '0.1807', 'learning_rate': '2.308e-05', 'entropy': '1.486', 'num_tokens': '1.355e+04', 'logits/chosen': '1.871', 'logits/rejected': '1.822', 'mean_token_accuracy': '0.6446', 'rewards/chosen': '0.2632', 'rewards/rejected': '-0.6175', 'rewards/accuracies': '0.375', 'rewards/margins': '0.8807', 'logps/chosen': '-95.32', 'logps/rejected': '-94.68', 'epoch': '0.64'}
{'loss': '0.3485', 'grad_norm': '0.291', 'learning_rate': '1.538e-05', 'entropy': '1.699', 'num_tokens': '1.733e+04', 'logits/chosen': '2.76', 'logits/rejected': '2.699', 'mean_token_accuracy': '0.5816', 'rewards/chosen': '0.5074', 'rewards/rejected': '-0.8978', 'rewards/accuracies': '0.5625', 'rewards/margins': '1.405', 'logps/chosen': '-147.6', 'logps/rejected': '-146', 'epoch': '0.8'}
{'loss': '0.4613', 'grad_norm': '0.2363', 'learning_rate': '7.692e-06', 'entropy': '1.65', 'num_tokens': '2.033e+04', 'logits/chosen': '2.498', 'logits/rejected': '2.389', 'mean_token_accuracy': '0.6144', 'rewards/chosen': '0.3124', 'rewards/rejected': '-0.6796', 'rewards/accuracies': '0.375', 'rewards/margins': '0.992', 'logps/chosen': '-101.9', 'logps/rejected': '-101.3', 'epoch': '0.96'}

Writing model shards: 100%|██████████████████████████████████████████| 1/1 [00:00<00:00,  2.53it/s]

{'train_runtime': '101.6', 'train_samples_per_second': '0.984', 'train_steps_per_second': '0.128', 'train_loss': '0.4477', 'entropy': '1.475', 'num_tokens': '2.155e+04', 'logits/chosen': '2.071', 'logits/rejected': '2.004', 'mean_token_accuracy': '0.6808', 'rewards/chosen': '0.3809', 'rewards/rejected': '-1.068', 'rewards/accuracies': '0.5', 'rewards/margins': '1.449', 'logps/chosen': '-160.7', 'logps/rejected': '-160.9', 'epoch': '1'}

TrainOutput(global_step=13, training_loss=0.44769501227598923, metrics={'train_runtime': 101.636, 'train_samples_per_second': 0.984, 'train_steps_per_second': 0.128, 'total_flos': 13772888987904.0, 'train_loss': 0.44769501227598923})